### ISSUE TITLE
Return of a local variable

### ISSUE THREAD

**Issue by emneo-dev** [UnchartRed/Libib#1]
This will crash for sure
https://github.com/UnchartRed/Libib/blob/86cbdfcdec8927921bb4dc4effcaa0ba4f0e51fc/ib/arr/ib_sort_int.c#L26

**Comment by RedGinor** [comment]
Assigning a local variable to a pointer one makes it possible to return it "safely"
https://github.com/UnchartRed/Libib/blob/86cbdfcdec8927921bb4dc4effcaa0ba4f0e51fc/ib/arr/ib_sort_int.c#L25

**Comment by emneo-dev** [comment]
This changes absolutely nothing, I'll get a snippet of code up and running to support my point
