### ISSUE TITLE
Big leak in ib_rev_str_arr

### ISSUE THREAD

**Issue by emneo-dev** [UnchartRed/Libib#4]
https://github.com/UnchartRed/Libib/blob/86cbdfcdec8927921bb4dc4effcaa0ba4f0e51fc/ib/arr/ib_rev_str_arr.c#L17
This malloc is after overwritten by the assignment 2 lines after
https://github.com/UnchartRed/Libib/blob/86cbdfcdec8927921bb4dc4effcaa0ba4f0e51fc/ib/arr/ib_rev_str_arr.c#L19

**Comment by RedGinor** [comment]
[FIX]
changed 'result' malloc value
https://github.com/UnchartRed/Libib/blob/19f4a5c2937ecf672c6b0675895808aee894faec/ib/arr/ib_rev_str_arr.c#L14 [FIX]
included 'ib_strdup' to automaticly copy strings
https://github.com/UnchartRed/Libib/blob/19f4a5c2937ecf672c6b0675895808aee894faec/ib/arr/ib_rev_str_arr.c#L17
