### ISSUE TITLE
Use symbolic links over bare copy in Makefile

### ISSUE THREAD

**Issue by emneo-dev** [UnchartRed/Libib#5]
Here it would be better to use a symbolic link instead of copying the whole file everytime
https://github.com/UnchartRed/Libib/blob/86cbdfcdec8927921bb4dc4effcaa0ba4f0e51fc/ib/Makefile#L50

**Comment by RedGinor** [comment]
Do you mean replacing this line
`scp ../includes/ib.h ../../includes `
by
`sl -fs ../includes/ib.h ../../includes/ib.h`

**Comment by emneo-dev** [comment]
ln instead of sl but yes
